# Generated by Django 6.0.3 on 2026-06-03 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_organization_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('kaggle', 'Kaggle'), ('local', 'Local')], max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('qurantine', 'Qurantine'), ('infected', 'Infected'), ('failed', 'Failed'), ('processing', 'Processing'), ('ready', 'Ready')], max_length=256)),
                ('column_schema', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
